OUTPUT:


ERROR:
Traceback (most recent call last):
  File "/home/ethan/repository/backup/LLM_Routing/llm/extra_info/solution/single/KTSP/15/city_15_instance_4/3/0/solution_r1.py", line 79, in <module>
    data_model = create_data_model(selected_indices)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ethan/repository/backup/LLM_Routing/llm/extra_info/solution/single/KTSP/15/city_15_instance_4/3/0/solution_r1.py", line 36, in create_data_model
    data['distance_matrix'] = distance_matrix[selected_indices][:, selected_codes]
                                                                   ^^^^^^^^^^^^^^
NameError: name 'selected_codes' is not defined. Did you mean: 'selected_indices'?


